#! /bin/zsh
# I'll be adding more commands soon

cyan=`tput setaf 6`
red=`tput setaf 1`
yellow=`tput setaf 3`



# for displaying System related process information

function showSys() 
{
	 ps auxw | grep System
}

# some compliments

function compliments() 
{
    tally=$RANDOM  # returns a psuedorandom integer
	range=15
	let "tally %= $range"

	if [ $tally -eq 0 ]
	then
		echo "$cyan You should be proud of yourself."
	elif [ $tally -eq 1 ]
	then
		echo "$cyan Your perspective is refreshing."
	elif [ $tally -eq 2 ]
	then
		echo "$cyan You're one of a kind."
	elif [ $tally -eq 3 ]
	then
		echo "$cyan You always make people smile."
	
	elif [ $tally -eq 4 ]
	then 
		echo "$cyan You are awesome."
		elif [ $tally -eq 5 ]
	then 
		echo "$cyan Nothing can stop you."
		elif [ $tally -eq 6 ]
	then 
		echo "$cyan You have the best sense of style."
		elif [ $tally -eq 7 ]
	then 
		echo "$cyan You are a great example to others."
		elif [ $tally -eq 8 ]
	then 
		echo "$cyan You are stunning."
		elif [ $tally -eq 9 ]
	then 
		echo "$cyan You’re a gift to everyone you meet."
		elif [ $tally -eq 10 ]
	then 
		echo "$cyan You’ve got great leadership skills."
		elif [ $tally -eq 11 ]
	then 
		echo "$cyan You have the best ideas."
		elif [ $tally -eq 12 ]
	then 
		echo "$cyan You really seem to know who you are. I admire that."
		elif [ $tally -eq 13 ]
	then 
		echo "$cyan Keep smiling."
		elif [ $tally -eq 14 ]
	then 
		echo "$cyan You can do it."
	fi

}


 # --------------------------------------------------------- #
 # Gets the users information.                               #
 # The account details.                                      #
 # Total no. of parameters: $#                               #
 # --------------------------------------------------------- # 

function GitDeets() 
{
	if [ $# -ne 1 ]; then
    echo "usage: $0 <username>"
    fi

	echo "$yellow ###################################################"

	curl -s "https://api.github.com/users/$1" | awk -F '"' '
 
   	/\"name\":/ {
  	 print " - Github User -> "$4"."
  	 }

   	/\"created_at\":/ {
   	print " - Account was created on "$4"."
   	 }

   	/\"updated_at\":/ {
   	print " - Account was updated on "$4"."
   	 }

 '
 	echo "$yellow ###################################################"

# exit 0

}

 # --------------------------------------------------------- #
 # Gets the tcp packets                                      #
 # --------------------------------------------------------- # 

function tcp() 
{
	netstat | awk '/^tcp/' 
}

 # --------------------------------------------------------- #
 # Gets the udp packets (udp4,udp6 and udp46)                #
 # --------------------------------------------------------- # 

function udp() 
{
	netstat | awk '/^udp/'
}

 # --------------------------------------------------------- #
 # displaying current network configuration                  #
 # --------------------------------------------------------- # 
function mip()
{
	curl ifconfig.me/all
}


 # --------------------------------------------------------- #
 # for displaying standard ports                             #
 # --------------------------------------------------------- # 

function ports()
{
	less /etc/services
}